--- #YAML:1.0
name:                Net-SFTP-Foreign
version:             0.90_19
abstract:            Secure File Transfer Protocol client
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Salvador Fandino <sfandino@yahoo.com>
